all: encoding decoding

encoding: encoding.cpp
	g++ -o encoding encoding.cpp -Wall -std=c++11 -O2

decoding: decoding.cpp
	g++ -o decoding decoding.cpp -Wall -std=c++11 -O2
	
clean:
	rm encoding decoding
